# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/npc/all/npc.rbi
#
# npc-0.0.1

module BF
end
module BF::IR
end
class BF::IR::Operation < NPC::Operation
end
class BF::IR::Program < NPC::NullaryOperation
  def body(*args, &blk); end
  def initialize(*args, &blk); end
  def results(*args, &blk); end
  extend T::Helpers
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  include NPC::NoResult
end
class BF::IR::Inc < NPC::NullaryOperation
  def initialize(*args, &blk); end
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  include NPC::NoResult
end
class BF::IR::Dec < BF::IR::Operation
end
class BF::IR::MoveL < BF::IR::Operation
end
class BF::IR::MoveR < BF::IR::Operation
end
class BF::IR::LoopL < BF::IR::Operation
end
class BF::IR::LoopR < BF::IR::Operation
end
class BF::IR::Print < BF::IR::Operation
end
class BF::IR::Add < BF::IR::Operation
end
class BF::IR::Sub < BF::IR::Operation
end
class BF::IR::Store < BF::IR::Operation
end
class BF::IR::Load < BF::IR::Operation
end
class BF::IR::Move < BF::IR::Operation
end
