# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/pry-sorbet/all/pry-sorbet.rbi
#
# pry-sorbet-0.2.1

module PrySorbet
end
class Pry
end
class Pry::Command
end
class Pry::Command::ShowInfo < Pry::ClassCommand
  def build_signature_string(signature); end
end
class Pry::Method
  def source_location; end
end
class PrySorbet::UnwrapCommand < Pry::ClassCommand
  def process; end
end
