# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: strong
module NPC::Operation::AnyResult; end
module NPC::Operation::Operands; end
module NPC::SignatureBuilder::OperandArray; end
module T::InterfaceWrapper::Helpers; end
module T::Private::Abstract::Hooks; end
module T::Private::Methods::MethodHooks; end
module T::Private::Methods::SingletonMethodHooks; end
module T::Private::MixesInClassMethods; end
